namespace BillingSystem.Infrastructure.Services.Localization;

public class LanguageService
{
    private string _currentLanguage = "ar";
    private Dictionary<string, Dictionary<string, string>> _translations = new();

    public event Action? OnLanguageChanged;

    public string CurrentLanguage => _currentLanguage;
    public bool IsArabic => _currentLanguage == "ar";
    public bool IsEnglish => _currentLanguage == "en";
    public string Direction => IsArabic ? "rtl" : "ltr";

    public LanguageService()
    {
        LoadTranslations();
    }

    private void LoadTranslations()
    {
        // Arabic translations
        _translations["ar"] = new Dictionary<string, string>
        {
            // Navigation
            ["Dashboard"] = "لوحة التحكم",
            ["Customers"] = "العملاء",
            ["Invoices"] = "الفواتير",
            ["Reports"] = "التقارير",
            ["Settings"] = "الإعدادات",
            ["Development"] = "التطوير",
            ["SeedData"] = "بيانات تجريبية",
            
            // Dashboard
            ["AnalyticsAndStatistics"] = "التحليلات والإحصائيات",
            ["TotalInvoices"] = "إجمالي الفواتير",
            ["Paid"] = "مدفوعة",
            ["Pending"] = "قيد الانتظار",
            ["Overdue"] = "متأخرة",
            ["Cancelled"] = "ملغاة",
            ["TotalCustomers"] = "العملاء",
            ["PaymentCount"] = "عدد المدفوعات",
            ["TotalPayments"] = "إجمالي المدفوعات",
            ["InvoiceStatusDistribution"] = "توزيع الفواتير حسب الحالة",
            ["PaymentsByMonth"] = "المدفوعات حسب الشهر",
            ["Top5Customers"] = "أعلى 5 عملاء حسب قيمة الفواتير",
            ["Total"] = "المجموع",
            
            // Customers
            ["AddCustomer"] = "إضافة عميل",
            ["CustomersList"] = "قائمة العملاء",
            ["SearchForCustomer"] = "البحث عن عميل...",
            
            // Invoices  
            ["AddInvoice"] = "إضافة فاتورة",
            ["InvoicesList"] = "قائمة الفواتير",
            ["InvoiceNumber"] = "رقم الفاتورة",
            ["SearchForInvoice"] = "البحث عن فاتورة...",
            ["FilterByStatus"] = "تصفية حسب الحالة",
            ["AllStatuses"] = "جميع الحالات",
            
            // Common Fields
            ["Search"] = "بحث",
            ["Name"] = "الاسم",
            ["Email"] = "البريد الإلكتروني",
            ["Phone"] = "الهاتف",
            ["Address"] = "العنوان",
            ["CreatedAt"] = "تاريخ الإنشاء",
            ["Actions"] = "الإجراءات",
            ["Customer"] = "العميل",
            ["DateIssued"] = "تاريخ الإصدار",
            ["DueDate"] = "تاريخ الاستحقاق",
            ["Status"] = "الحالة",
            ["Amount"] = "المبلغ",
            
            // Actions
            ["Edit"] = "تعديل",
            ["Delete"] = "حذف",
            ["Cancel"] = "إلغاء",
            ["Save"] = "حفظ",
            ["Close"] = "إغلاق",
            ["View"] = "عرض",
            ["Print"] = "طباعة",
            ["Download"] = "تحميل",
            ["Generate"] = "إنشاء",
            ["Filter"] = "تصفية",
            ["Export"] = "تصدير",
            
            // Messages
            ["Loading"] = "جاري التحميل...",
            ["NoData"] = "لا توجد بيانات",
            ["Error"] = "خطأ",
            ["Success"] = "نجح",
            ["Warning"] = "تحذير",
            ["Info"] = "معلومات",
            ["InvalidCredentials"] = "البريد الإلكتروني أو كلمة المرور غير صحيحة",
            ["PasswordMismatch"] = "كلمة المرور غير متطابقة",
            ["PasswordTooShort"] = "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
            ["ConfirmDelete"] = "تأكيد الحذف",
            ["DeleteInvoiceConfirmation"] = "هل أنت متأكد من حذف الفاتورة '{0}'؟",
            ["Yes"] = "نعم",
            ["InvoiceDeletedSuccessfully"] = "تم حذف الفاتورة بنجاح",
            ["ErrorDeletingInvoice"] = "حدث خطأ أثناء حذف الفاتورة",
            ["EmailSentSuccessfully"] = "✅ تم إرسال الفاتورة بالبريد الإلكتروني بنجاح إلى العميل",
            ["ErrorSendingEmail"] = "❌ فشل إرسال الفاتورة بالبريد الإلكتروني",
            ["EmailAlreadyExists"] = "البريد الإلكتروني مسجل مسبقاً",
            ["RegistrationFailed"] = "فشل إنشاء الحساب، يرجى المحاولة مرة أخرى",
            ["NetworkError"] = "خطأ في الاتصال بالشبكة",
            ["UnknownError"] = "حدث خطأ غير متوقع",
            ["CustomerNotFound"] = "العميل غير موجود",
            ["CustomerAddedSuccessfully"] = "تم إضافة العميل بنجاح",
            ["CustomerUpdatedSuccessfully"] = "تم تحديث بيانات العميل بنجاح",
            ["CustomerDeletedSuccessfully"] = "تم حذف العميل بنجاح",
            ["ErrorDeletingCustomer"] = "حدث خطأ أثناء حذف العميل",
            ["NameRequired"] = "اسم العميل مطلوب",
            ["InvalidEmail"] = "البريد الإلكتروني غير صالح",
            ["ConfirmDeleteCustomer"] = "هل أنت متأكد من حذف العميل '{0}'؟",
            
            // PDF and Email Messages  
            ["PdfDownloadedSuccessfully"] = "✅ تم تحميل ملف PDF بنجاح",
            ["ErrorDownloadingPdf"] = "❌ فشل تحميل ملف PDF",
            ["NoEmailForCustomer"] = "⚠️ لا يوجد بريد إلكتروني مسجل لهذا العميل",

            // Invoices & Payments Messages
            ["InvoiceNotFound"] = "الفاتورة غير موجودة",
            ["CustomerRequired"] = "العميل مطلوب",
            ["InvoiceItemsRequired"] = "يجب إضافة بند واحد على الأقل",
            ["InvoiceAddedSuccessfully"] = "تم إضافة الفاتورة بنجاح",
            ["InvoiceUpdatedSuccessfully"] = "تم تحديث الفاتورة بنجاح",
            ["RemainingHelperText"] = "المتبقي: {0} ₪",
            ["Cash"] = "نقدي",
            ["CreditCard"] = "بطاقة ائتمان",
            ["BankTransfer"] = "تحويل بنكي",
            ["Check"] = "شيك",
            ["Other"] = "أخرى",
            ["ReferenceHelperText"] = "رقم الشيك أو رقم المعاملة",
            ["NoPaymentsForInvoice"] = "لا توجد مدفوعات لهذه الفاتورة",
            ["ErrorLoadingData"] = "خطأ في تحميل البيانات",
            ["AddPaymentTitle"] = "إضافة دفعة",
            ["PaymentAddedSuccessfully"] = "تم إضافة الدفعة بنجاح",
            ["ConfirmDeletePayment"] = "هل تريد حذف هذه الدفعة ({0} ₪)؟",
            ["PaymentDeletedSuccessfully"] = "تم حذف الدفعة بنجاح",
            
            // Seed Data
            ["SeedDataPage"] = "بيانات تجريبية",
            ["SeedDataDescription"] = "إضافة بيانات تجريبية إلى النظام للاختبار",
            ["AddSampleData"] = "إضافة البيانات التجريبية",
            ["DataAlreadyExists"] = "البيانات موجودة مسبقاً",
            ["WhatWillBeAdded"] = "ما سيتم إضافته",
            ["SampleCustomers"] = "عملاء تجريبيون",
            ["SampleInvoices"] = "فواتير تجريبية",
            ["SamplePayments"] = "دفعات تجريبية",
            
            // Reports
            ["CustomersReport"] = "تقرير العملاء",
            ["InvoicesReport"] = "تقرير الفواتير",
            ["PaymentsReport"] = "تقرير المدفوعات",
            ["TotalInvoicesValue"] = "إجمالي قيمة الفواتير",
            ["TotalPaymentsReceived"] = "إجمالي المدفوعات المستلمة",
            ["RemainingBalance"] = "الرصيد المتبقي",
            ["AveragePayment"] = "متوسط قيمة الدفعة",
            ["PaymentMethod"] = "طريقة الدفع",
            ["PaymentDate"] = "تاريخ الدفعة",
            ["From"] = "من",
            ["To"] = "إلى",
            ["DateRange"] = "نطاق التاريخ",
            ["AllMethods"] = "جميع الطرق",
            
            // Forms & Editing
            ["NewCustomer"] = "عميل جديد",
            ["EditCustomer"] = "تعديل عميل",
            ["CustomerInformation"] = "معلومات العميل",
            ["NewInvoice"] = "فاتورة جديدة",
            ["EditInvoice"] = "تعديل فاتورة",
            ["DeleteInvoice"] = "حذف فاتورة",
            ["ManagePayments"] = "إدارة الدفعات",
            ["DownloadPdf"] = "تحميل PDF",
            ["SendEmail"] = "إرسال بالبريد",
            ["InvoiceDetails"] = "تفاصيل الفاتورة",
            ["InvoiceItems"] = "بنود الفاتورة",
            ["AddItem"] = "إضافة بند",
            ["Item"] = "البند",
            ["Description"] = "الوصف",
            ["Quantity"] = "الكمية",
            ["UnitPrice"] = "سعر الوحدة",
            ["TotalAmount"] = "المبلغ الإجمالي",
            ["Notes"] = "ملاحظات",
            ["SelectCustomer"] = "اختر العميل",
            ["Required"] = "مطلوب",
            
            // Payments
            ["AddPayment"] = "إضافة دفعة",
            ["PaymentHistory"] = "سجل المدفوعات",
            ["PaidAmount"] = "المبلغ المدفوع",
            ["RemainingAmount"] = "المتبقي",
            ["Date"] = "التاريخ",
            ["Method"] = "الطريقة",
            ["Reference"] = "المرجع",
            ["Back"] = "رجوع",
            ["Invoice"] = "الفاتورة",
            
            // Users
            ["UserManagement"] = "إدارة المستخدمين",
            ["AddUser"] = "إضافة مستخدم",
            ["SearchByNameOrEmail"] = "بحث بالاسم أو البريد الإلكتروني",
            ["Role"] = "الدور",
            ["AllRoles"] = "جميع الأدوار",
            ["Admin"] = "مدير",
            ["Accountant"] = "محاسب",
            
            // Auth Pages
            ["WelcomeBack"] = "مرحباً بعودتك!",
            ["SignInToContinue"] = "سجل دخولك للمتابعة إلى نظام الفواتير",
            ["EmailAddress"] = "البريد الإلكتروني",
            ["Password"] = "كلمة المرور",
            ["SignIn"] = "تسجيل الدخول",
            ["SigningIn"] = "جاري تسجيل الدخول...",
            ["DontHaveAccount"] = "ليس لديك حساب؟",
            ["SignUp"] = "إنشاء حساب",
            ["CreateAccount"] = "إنشاء حساب",
            ["JoinUs"] = "انضم إلينا وابدأ بإدارة نظام الفواتير",
            ["FullName"] = "الاسم الكامل",
            ["ConfirmPassword"] = "تأكيد كلمة المرور",
            ["AccountType"] = "نوع الحساب",
            ["Administrator"] = "مدير النظام",
            ["CreatingAccount"] = "جاري إنشاء الحساب...",
            ["AlreadyHaveAccount"] = "لديك حساب بالفعل؟",
            ["Logout"] = "تسجيل خروج",
            
            // Landing Page
            ["BillingSystemTitle"] = "نظام الفواتير الاحترافي",
            ["BillingSystemSubtitle"] = "إدارة فواتيرك ومدفوعاتك وعملائك بسهولة وكفاءة",
            ["Features"] = "المميزات",
            ["CustomerManagement"] = "إدارة العملاء",
            ["CustomerManagementDesc"] = "إدارة بيانات العملاء بشكل كامل ومنظم",
            ["InvoiceManagement"] = "إدارة الفواتير",
            ["InvoiceManagementDesc"] = "إنشاء وتتبع الفواتير بكل سهولة",
            ["PaymentTracking"] = "تتبع المدفوعات",
            ["PaymentTrackingDesc"] = "متابعة المدفوعات والمستحقات",
            ["ReportsDesc"] = "تقارير شاملة ومفصلة",
            ["PDFGeneration"] = "توليد PDF",
            ["PDFGenerationDesc"] = "تصدير الفواتير إلى ملفات PDF",
            ["MultiLanguage"] = "متعدد اللغات",
            ["MultiLanguageDesc"] = "دعم العربية والإنجليزية",
            ["QuickLinks"] = "روابط سريعة",
            ["Contact"] = "تواصل معنا",

            // New Home Page Keys
            ["GetStarted"] = "ابدأ الآن",
            ["HappyCustomers"] = "عميل سعيد",
            ["InvoicesGenerated"] = "فاتورة تم إنشاؤها",
            ["Uptime"] = "وقت التشغيل",
            ["WhyChooseUs"] = "لماذا تختارنا؟",
            ["WhyChooseUsDesc"] = "نحن نقدم أفضل الحلول لإدارة فواتيرك ومدفوعاتك بكل سهولة وأمان.",
            ["FastInvoicing"] = "فواتير سريعة",
            ["FastInvoicingDesc"] = "أنشئ وأرسل الفواتير لعملائك في ثوانٍ معدودة.",
            ["SecurePayments"] = "مدفوعات آمنة",
            ["SecurePaymentsDesc"] = "نظام آمن وموثوق لتتبع جميع مدفوعاتك.",
            ["SmartAnalytics"] = "تحليلات ذكية",
            ["SmartAnalyticsDesc"] = "احصل على رؤى قيمة حول أداء عملك المالي.",
            ["ReadyToStart"] = "مستعد للبدء؟",
            ["JoinThousands"] = "انضم إلى آلاف الشركات التي تثق بنا لإدارة فواتيرها.",
            ["CreateFreeAccount"] = "أنشئ حساب مجاني",
            ["FooterDesc"] = "نظام الفواتير هو الحل الأمثل لإدارة أعمالك المالية بكفاءة.",
            ["Home"] = "الرئيسية",
            ["Pricing"] = "الأسعار",
            
            // Language
            ["Language"] = "اللغة",
            ["SwitchToEnglish"] = "Switch to English",
            ["SwitchToArabic"] = "التبديل للعربية",
            
            ["AdminDashboard"] = "لوحة تحكم الإدارة",
            ["SystemMonitoring"] = "مراقبة النظام والإشراف",
            ["LiveStatus"] = "حالة النظام الحية",
            ["ManageUsers"] = "إدارة المستخدمين",
            ["ViewCustomers"] = "عرض العملاء",
            ["CheckInvoices"] = "فحص الفواتير",
            ["TrackPayments"] = "تتبع المدفوعات",
            ["QuickStats"] = "إحصائيات سريعة",
            ["TablesCount"] = "عدد الجداول",
            ["DBVersion"] = "إصدار قاعدة البيانات",
            ["SystemOverview"] = "نظرة عامة على النظام",
            ["GeneralSettings"] = "الإعدادات العامة",
            ["CompanyName"] = "اسم الشركة",
            ["CurrencySymbol"] = "رمز العملة",
            ["DefaultTaxRate"] = "نسبة الضريبة الافتراضية (%)",
            ["SystemControl"] = "التحكم بالنظام",
            ["MaintenanceMode"] = "وضع الصيانة",
            ["AllowRegistrations"] = "السماح بالتسجيل الجديد",
            ["DataManagement"] = "إدارة البيانات",
            ["ExportAllData"] = "تصدير جميع البيانات (JSON)",
            ["SaveSettings"] = "حفظ الإعدادات",
            ["SettingsSaved"] = "تم حفظ الإعدادات بنجاح",
            ["DataExported"] = "تم تصدير البيانات بنجاح",
            ["AuditLogs"] = "سجل التدقيق",
            ["Action"] = "الإجراء",
            ["Entity"] = "الكيان",
            ["Details"] = "التفاصيل",
            ["Timestamp"] = "الوقت",
            ["IPAddress"] = "عنوان IP",
            ["NoAuditLogs"] = "لا توجد سجلات",
            ["WelcomeTo"] = "مرحباً بك في",
            ["HomeSubtitle"] = "الحل الأمثل لإدارة الفواتير والمدفوعات",
            ["HomeDescription"] = "نظام متكامل لإدارة الفواتير، المدفوعات، والتقارير بكفاءة عالية وأمان مطلق.",
            ["GetStarted"] = "ابدأ الآن",
            ["LearnMore"] = "اعرف المزيد",
            ["KeyFeatures"] = "الميزات الرئيسية",
            ["FastAndEfficient"] = "سريع وفعال",
            ["FastDescription"] = "أداء عالي واستجابة فورية",
            ["SecureAndReliable"] = "آمن وموثوق",
            ["SecureDescription"] = "حماية بياناتك بأعلى معايير الأمان",
            ["RealTimeReports"] = "تقارير لحظية",
            ["ReportsDescription"] = "تحليلات وتقارير فورية ودقيقة",
            ["MultiLanguage"] = "دعم متعدد اللغات",
            ["LanguageDescription"] = "عربي وإنجليزي بسلاسة تامة",
            ["ActiveUsers"] = "مستخدم نشط",
            ["InvoicesProcessed"] = "فاتورة معالجة",
            ["Uptime"] = "وقت التشغيل",
            ["Support"] = "دعم فني",
            ["ReadyToStart"] = "جاهز للبدء؟",
            ["CTADescription"] = "انضم إلى آلاف الشركات التي تثق في نظامنا",
            ["CreateAccount"] = "إنشاء حساب",
            ["UserGrowth"] = "نمو المستخدمين",
            ["RevenueAnalytics"] = "تحليلات الإيرادات",
            ["RecentActivity"] = "النشاطات الأخيرة",
            ["SystemHealth"] = "صحة النظام",
            ["DatabaseSize"] = "حجم قاعدة البيانات",
            ["TotalRecords"] = "إجمالي السجلات",
            ["UserRoleDistribution"] = "توزيع المستخدمين حسب الدور",
            ["TotalUsers"] = "إجمالي المستخدمين",
            ["CollectionRate"] = "معدل التحصيل",
            ["AverageInvoiceValue"] = "متوسط قيمة الفاتورة",
            ["Revenue"] = "الإيرادات",
            ["NoRecentActivity"] = "لا توجد نشاطات حديثة",
            ["Payments"] = "المدفوعات",
            ["Refresh"] = "تحديث",
        };

        // English translations
        _translations["en"] = new Dictionary<string, string>
        {
            // Navigation
            ["Dashboard"] = "Dashboard",
            ["Customers"] = "Customers",
            ["Invoices"] = "Invoices",
            ["Reports"] = "Reports",
            ["Settings"] = "Settings",
            ["Development"] = "Development",
            ["SeedData"] = "Seed Data",
            
            // Dashboard
            ["AnalyticsAndStatistics"] = "Analytics and Statistics",
            ["TotalInvoices"] = "Total Invoices",
            ["Paid"] = "Paid",
            ["Pending"] = "Pending",
            ["Overdue"] = "Overdue",
            ["Cancelled"] = "Cancelled",
            ["TotalCustomers"] = "Customers",
            ["PaymentCount"] = "Payment Count",
            ["TotalPayments"] = "Total Payments",
            ["InvoiceStatusDistribution"] = "Invoice Status Distribution",
            ["PaymentsByMonth"] = "Payments by Month",
            ["Top5Customers"] = "Top 5 Customers by Invoice Value",
            ["Total"] = "Total",
            
            // Customers
            ["AddCustomer"] = "Add Customer",
            ["CustomersList"] = "Customers List",
            ["SearchForCustomer"] = "Search for customer...",
            
            // Invoices
            ["AddInvoice"] = "Add Invoice",
            ["InvoicesList"] = "Invoices List",
            ["InvoiceNumber"] = "Invoice Number",
            ["SearchForInvoice"] = "Search for invoice...",
            ["FilterByStatus"] = "Filter by Status",
            ["AllStatuses"] = "All Statuses",
            
            // Common Fields
            ["Search"] = "Search",
            ["Name"] = "Name",
            ["Email"] = "Email",
            ["Phone"] = "Phone",
            ["Address"] = "Address",
            ["CreatedAt"] = "Created At",
            ["Actions"] = "Actions",
            ["Customer"] = "Customer",
            ["DateIssued"] = "Date Issued",
            ["DueDate"] = "Due Date",
            ["Status"] = "Status",
            ["Amount"] = "Amount",
            
            // Actions
            ["Edit"] = "Edit",
            ["Delete"] = "Delete",
            ["Cancel"] = "Cancel",
            ["Save"] = "Save",
            ["Close"] = "Close",
            ["View"] = "View",
            ["Print"] = "Print",
            ["Download"] = "Download",
            ["Generate"] = "Generate",
            ["Filter"] = "Filter",
            ["Export"] = "Export",
            
            // Messages
            ["Loading"] = "Loading...",
            ["NoData"] = "No data available",
            ["Error"] = "Error",
            ["Success"] = "Success",
            ["Warning"] = "Warning",
            ["Info"] = "Info",
            ["InvalidCredentials"] = "Invalid email or password",
            ["PasswordMismatch"] = "Passwords do not match",
            ["PasswordTooShort"] = "Password must be at least 6 characters",
            ["ConfirmDelete"] = "Confirm Delete",
            ["DeleteInvoiceConfirmation"] = "Are you sure you want to delete invoice '{0}'?",
            ["Yes"] = "Yes",
            ["InvoiceDeletedSuccessfully"] = "Invoice deleted successfully",
            ["ErrorDeletingInvoice"] = "Error occurred while deleting invoice",
            ["EmailSentSuccessfully"] = "✅ Invoice email sent successfully to customer",
            ["ErrorSendingEmail"] = "❌ Failed to send invoice email",
            ["EmailAlreadyExists"] = "Email is already registered",
            ["RegistrationFailed"] = "Registration failed, please try again",
            ["NetworkError"] = "Network connection error",
            ["UnknownError"] = "An unexpected error occurred",
            ["CustomerNotFound"] = "Customer not found",
            ["CustomerAddedSuccessfully"] = "Customer added successfully",
            ["CustomerUpdatedSuccessfully"] = "Customer updated successfully",
            ["CustomerDeletedSuccessfully"] = "Customer deleted successfully",
            ["ErrorDeletingCustomer"] = "Error deleting customer",
            ["NameRequired"] = "Customer name is required",
            ["InvalidEmail"] = "Invalid email address",
            ["ConfirmDeleteCustomer"] = "Are you sure you want to delete customer '{0}'?",
            
            // PDF and Email Messages
            ["PdfDownloadedSuccessfully"] = "✅ PDF file downloaded successfully",
            ["ErrorDownloadingPdf"] = "❌ Failed to download PDF file",
            ["NoEmailForCustomer"] = "⚠️ No email address registered for this customer",

            // Invoices & Payments Messages
            ["InvoiceNotFound"] = "Invoice not found",
            ["CustomerRequired"] = "Customer is required",
            ["InvoiceItemsRequired"] = "At least one item is required",
            ["InvoiceAddedSuccessfully"] = "Invoice added successfully",
            ["InvoiceUpdatedSuccessfully"] = "Invoice updated successfully",
            ["RemainingHelperText"] = "Remaining: {0} ₪",
            ["Cash"] = "Cash",
            ["CreditCard"] = "Credit Card",
            ["BankTransfer"] = "Bank Transfer",
            ["Check"] = "Check",
            ["Other"] = "Other",
            ["ReferenceHelperText"] = "Check number or transaction ID",
            ["NoPaymentsForInvoice"] = "No payments found for this invoice",
            ["ErrorLoadingData"] = "Error loading data",
            ["AddPaymentTitle"] = "Add Payment",
            ["PaymentAddedSuccessfully"] = "Payment added successfully",
            ["ConfirmDeletePayment"] = "Are you sure you want to delete this payment ({0} ₪)?",
            ["PaymentDeletedSuccessfully"] = "Payment deleted successfully",
            
            // Seed Data
            ["SeedDataPage"] = "Seed Data",
            ["SeedDataDescription"] = "Add sample data to the system for testing",
            ["AddSampleData"] = "Add Sample Data",
            ["DataAlreadyExists"] = "Data Already Exists",
            ["WhatWillBeAdded"] = "What Will Be Added",
            ["SampleCustomers"] = "Sample Customers",
            ["SampleInvoices"] = "Sample Invoices",
            ["SamplePayments"] = "Sample Payments",
            
            // Reports
            ["CustomersReport"] = "Customers Report",
            ["InvoicesReport"] = "Invoices Report",
            ["PaymentsReport"] = "Payments Report",
            ["TotalInvoicesValue"] = "Total Invoices Value",
            ["TotalPaymentsReceived"] = "Total Payments Received",
            ["RemainingBalance"] = "Remaining Balance",
            ["AveragePayment"] = "Average Payment",
            ["PaymentMethod"] = "Payment Method",
            ["PaymentDate"] = "Payment Date",
            ["From"] = "From",
            ["To"] = "To",
            ["DateRange"] = "Date Range",
            ["AllMethods"] = "All Methods",
            
            // Forms & Editing
            ["NewCustomer"] = "New Customer",
            ["EditCustomer"] = "Edit Customer",
            ["CustomerInformation"] = "Customer Information",
            ["NewInvoice"] = "New Invoice",
            ["EditInvoice"] = "Edit Invoice",
            ["DeleteInvoice"] = "Delete Invoice",
            ["ManagePayments"] = "Manage Payments",
            ["DownloadPdf"] = "Download PDF",
            ["SendEmail"] = "Send Email",
            ["InvoiceDetails"] = "Invoice Details",
            ["InvoiceItems"] = "Invoice Items",
            ["AddItem"] = "Add Item",
            ["Item"] = "Item",
            ["Description"] = "Description",
            ["Quantity"] = "Quantity",
            ["UnitPrice"] = "Unit Price",
            ["TotalAmount"] = "Total Amount",
            ["Notes"] = "Notes",
            ["SelectCustomer"] = "Select Customer",
            ["Required"] = "Required",
            
            // Payments
            ["AddPayment"] = "Add Payment",
            ["PaymentHistory"] = "Payment History",
            ["PaidAmount"] = "Paid Amount",
            ["RemainingAmount"] = "Remaining",
            ["Date"] = "Date",
            ["Method"] = "Method",
            ["Reference"] = "Reference",
            ["Back"] = "Back",
            ["Invoice"] = "Invoice",
            
            // Users
            ["UserManagement"] = "User Management",
            ["AddUser"] = "Add User",
            ["SearchByNameOrEmail"] = "Search by name or email",
            ["Role"] = "Role",
            ["AllRoles"] = "All Roles",
            ["Admin"] = "Admin",
            ["Accountant"] = "Accountant",
            
            // Auth Pages
            ["WelcomeBack"] = "Welcome Back!",
            ["SignInToContinue"] = "Sign in to continue to Billing System",
            ["EmailAddress"] = "Email Address",
            ["Password"] = "Password",
            ["SignIn"] = "Sign In",
            ["SigningIn"] = "Signing in...",
            ["DontHaveAccount"] = "Don't have an account?",
            ["SignUp"] = "Sign Up",
            ["CreateAccount"] = "Create Account",
            ["JoinUs"] = "Join us and start managing your billing system",
            ["FullName"] = "Full Name",
            ["ConfirmPassword"] = "Confirm Password",
            ["AccountType"] = "Account Type",
            ["Administrator"] = "Administrator",
            ["CreatingAccount"] = "Creating account...",
            ["AlreadyHaveAccount"] = "Already have an account?",
            ["Logout"] = "Logout",
            
            // Landing Page
            ["BillingSystemTitle"] = "Professional Billing System",
            ["BillingSystemSubtitle"] = "Manage your invoices, payments, and customers with ease and efficiency",
            ["Features"] = "Features",
            ["CustomerManagement"] = "Customer Management",
            ["CustomerManagementDesc"] = "Manage customer data completely and organized",
            ["InvoiceManagement"] = "Invoice Management",
            ["InvoiceManagementDesc"] = "Create and track invoices with ease",
            ["PaymentTracking"] = "Payment Tracking",
            ["PaymentTrackingDesc"] = "Monitor payments and receivables",
            ["ReportsDesc"] = "Comprehensive and detailed reports",
            ["PDFGeneration"] = "PDF Generation",
            ["PDFGenerationDesc"] = "Export invoices to PDF files",
            ["MultiLanguage"] = "Multi-Language",
            ["MultiLanguageDesc"] = "Support for Arabic and English",
            ["QuickLinks"] = "Quick Links",
            ["Contact"] = "Contact",

            // New Home Page Keys
            ["GetStarted"] = "Get Started",
            ["HappyCustomers"] = "Happy Customers",
            ["InvoicesGenerated"] = "Invoices Generated",
            ["Uptime"] = "Uptime",
            ["WhyChooseUs"] = "Why Choose Us?",
            ["WhyChooseUsDesc"] = "We provide the best solutions to manage your invoices and payments with ease and security.",
            ["FastInvoicing"] = "Fast Invoicing",
            ["FastInvoicingDesc"] = "Create and send invoices to your customers in seconds.",
            ["SecurePayments"] = "Secure Payments",
            ["SecurePaymentsDesc"] = "Secure and reliable system to track all your payments.",
            ["SmartAnalytics"] = "Smart Analytics",
            ["SmartAnalyticsDesc"] = "Get valuable insights into your business financial performance.",
            ["ReadyToStart"] = "Ready to Start?",
            ["JoinThousands"] = "Join thousands of businesses that trust us to manage their billing.",
            ["CreateFreeAccount"] = "Create Free Account",
            ["FooterDesc"] = "Billing System is the perfect solution to manage your financial business efficiently.",
            ["Home"] = "Home",
            ["Pricing"] = "Pricing",
            
            // Language
            ["Language"] = "Language",
            ["SwitchToEnglish"] = "Switch to English",
            ["SwitchToArabic"] = "التبديل للعربية",
            
            // Admin Dashboard
            ["AdminDashboard"] = "Admin Dashboard",
            ["SystemMonitoring"] = "System Monitoring & Oversight",
            ["LiveStatus"] = "Live System Status",
            ["ManageUsers"] = "Manage Users",
            ["ViewCustomers"] = "View Customers",
            ["CheckInvoices"] = "Check Invoices",
            ["TrackPayments"] = "Track Payments",
            ["QuickStats"] = "Quick Stats",
            ["TablesCount"] = "Tables Count",
            ["DBVersion"] = "DB Version",
            ["SystemOverview"] = "System Overview",
            ["GeneralSettings"] = "General Settings",
            ["CompanyName"] = "Company Name",
            ["CurrencySymbol"] = "Currency Symbol",
            ["DefaultTaxRate"] = "Default Tax Rate (%)",
            ["SystemControl"] = "System Control",
            ["MaintenanceMode"] = "Maintenance Mode",
            ["AllowRegistrations"] = "Allow New Registrations",
            ["DataManagement"] = "Data Management",
            ["ExportAllData"] = "Export All Data (JSON)",
            ["SaveSettings"] = "Save Settings",
            ["SettingsSaved"] = "Settings saved successfully",
            ["DataExported"] = "Data exported successfully",
            ["AuditLogs"] = "Audit Logs",
            ["Action"] = "Action",
            ["Entity"] = "Entity",
            ["Details"] = "Details",
            ["Timestamp"] = "Timestamp",
            ["IPAddress"] = "IP Address",
            ["NoAuditLogs"] = "No audit logs found",
            ["WelcomeTo"] = "Welcome to",
            ["HomeSubtitle"] = "The Ultimate Solution for Invoice & Payment Management",
            ["HomeDescription"] = "A comprehensive system for managing invoices, payments, and reports with high efficiency and absolute security.",
            ["GetStarted"] = "Get Started",
            ["LearnMore"] = "Learn More",
            ["KeyFeatures"] = "Key Features",
            ["FastAndEfficient"] = "Fast & Efficient",
            ["FastDescription"] = "High performance and instant response",
            ["SecureAndReliable"] = "Secure & Reliable",
            ["SecureDescription"] = "Protect your data with highest security standards",
            ["RealTimeReports"] = "Real-Time Reports",
            ["ReportsDescription"] = "Instant and accurate analytics and reports",
            ["MultiLanguage"] = "Multi-Language Support",
            ["LanguageDescription"] = "Arabic and English seamlessly",
            ["ActiveUsers"] = "Active Users",
            ["InvoicesProcessed"] = "Invoices Processed",
            ["Uptime"] = "Uptime",
            ["Support"] = "Support",
            ["ReadyToStart"] = "Ready to Start?",
            ["CTADescription"] = "Join thousands of companies that trust our system",
            ["CreateAccount"] = "Create Account",
            ["UserGrowth"] = "User Growth",
            ["RevenueAnalytics"] = "Revenue Analytics",
            ["RecentActivity"] = "Recent Activity",
            ["SystemHealth"] = "System Health",
            ["DatabaseSize"] = "Database Size",
            ["TotalRecords"] = "Total Records",
            ["UserRoleDistribution"] = "User Role Distribution",
            ["TotalUsers"] = "Total Users",
            ["CollectionRate"] = "Collection Rate",
            ["AverageInvoiceValue"] = "Average Invoice Value",
            ["Revenue"] = "Revenue",
            ["NoRecentActivity"] = "No recent activity",
            ["Payments"] = "Payments",
            ["Refresh"] = "Refresh",
        };
    }

    public void SetLanguage(string language)
    {
        if (language != "ar" && language != "en")
            return;

        _currentLanguage = language;
        OnLanguageChanged?.Invoke();
    }

    public void ToggleLanguage()
    {
        SetLanguage(_currentLanguage == "ar" ? "en" : "ar");
    }

    public string GetText(string key)
    {
        if (_translations.ContainsKey(_currentLanguage) && 
            _translations[_currentLanguage].ContainsKey(key))
        {
            return _translations[_currentLanguage][key];
        }
        
        return key; // Return key if translation not found
    }

    public string this[string key] => GetText(key);
}
